### ISSUE TITLE
Missing files in master?

### ISSUE THREAD

**Issue by cortho** [owncloud/guests#101]
In this commit https://github.com/owncloud/guests/commit/1a7c916e351204f8987376e842b6c2feb68db3d2 there should be a file guests.bundle.js as requested at https://github.com/owncloud/guests/blob/master/appinfo/app.php#L23 but it is not in master. (I guess this should be replacing app.js and vue.js)

Current master does not work.

 @felixheidecke any help?

**Comment by DeepDiver1975** [comment]
> guests.bundle.js

this file has to be build using the webpack tools.

@felixheidecke @IljaN please add a Makefile which builds the app and the app package. THX

**Comment by cortho** [comment]
of course. thanks a lot

**Comment by cortho** [comment]
basically a duplicate of https://github.com/owncloud/guests/issues/24 -> closing
