### ISSUE TITLE
The email provided for a guest user should be checked that has a right email address format

### ISSUE THREAD

**Issue by davitol** [owncloud/guests#111]
Using PR https://github.com/owncloud/guests/pull/109

![screen shot 2017-07-18 at 10 49 22](https://user-images.githubusercontent.com/10596560/28308580-ede4a712-6ba6-11e7-84fb-fbb0040ed86a.png)

@cortho

**Comment by cortho** [comment]
Basically this is a correct email address, same as user@localhost. In addition to that, there is a check for valid addresses at https://github.com/cortho/guests/blob/new_registration/controller/userscontroller.php#L103

This still is an issue?

**Comment by davitol** [comment]
What about guest@owncloud.com.com ? It seems to be accepted. As said it is only an enhancement.

**Comment by cortho** [comment]
Even this is a valid email address since the domain com.com is registered.

**Comment by davitol** [comment]
👍 OK Let's close it
