### ISSUE TITLE
It is possible to erase core app from guests whitelist

### ISSUE THREAD

**Issue by davitol** [owncloud/guests#112]
![screen shot 2017-07-18 at 17 03 28](https://user-images.githubusercontent.com/10596560/28324398-89747340-6bdb-11e7-904e-6380bcefcb65.png)

Editing this line it is possible to delete core app that will make nonsense to have guest users only for get this screen, and cannot deploy no further action.

![screen shot 2017-07-18 at 16 46 44](https://user-images.githubusercontent.com/10596560/28324543-f927a5cc-6bdb-11e7-8610-3ca175726432.png)

@cortho

**Comment by davitol** [comment]
Also if we delete the first comma of the list, or if we add an app name at the beggining, the guests account are no longer available

**Comment by cortho** [comment]
Most probably we should move the comma and core to the backend and have the whitelist only display apps, which actually can be removed.

We'll need this anyway, when we want to implement https://github.com/owncloud/guests/issues/106

**Comment by pmaier1** [comment]
Valid points!

**Comment by cortho** [comment]
PR: https://github.com/owncloud/guests/pull/127

**Comment by cortho** [comment]
fixed with #127
