### ISSUE TITLE
It should not be possible to set an empty name to the guests user group

### ISSUE THREAD

**Issue by davitol** [owncloud/guests#113]
Using https://github.com/owncloud/guests/pull/109

It should not be possible to set an empty name to the guests user group

![screen shot 2017-07-18 at 17 12 03](https://user-images.githubusercontent.com/10596560/28324764-72e99a00-6bdc-11e7-97a0-91dd663cc324.png)

User Menu with Guest User Group set to empty

![guestempty](https://user-images.githubusercontent.com/10596560/28324779-815c3b10-6bdc-11e7-80d5-fa2ce7c9cbc1.gif)

@cortho

**Comment by cortho** [comment]
PR here: https://github.com/owncloud/guests/pull/117

**Comment by cortho** [comment]
fixed with #117
