### ISSUE TITLE
Guests users can create other guests users

### ISSUE THREAD

**Issue by davitol** [owncloud/guests#114]
With the currents Guests app approach . A guest user is able to create another guest user. Is this the intended behaviour? Have we considered the impact of this decision about creating guest users in this way? @pmaier1 FYI @cortho 

Impl concept here: https://github.com/owncloud/guests/issues/114#issuecomment-341802055

**Comment by cortho** [comment]
I think this should be prevented. Quote from this page https://owncloud.com/owncloud-x-new-generation-owncloud-focussing-security-performance-productivity-marketplace-offers-flexibility-extensions/

> [...] the guest can take full advantage of the desktop client without, however, owning any files or being able to share files with other users or guests within the system.

**Comment by cortho** [comment]
@davitol how did you manage to create another guest user as a guest?

Looking at the code, sharing is disabled for guests, see https://github.com/owncloud/guests/blob/master/lib/groupbackend.php#L184
Plus, when I open the sharetab as a guest user it reads _Resharing is not allowed_

**Comment by pmaier1** [comment]
> Plus, when I open the sharetab as a guest user it reads Resharing is not allowed

Do you maybe have resharing disabled in sharing settings? Actually guests should be able to reshare if permission is given by the original sharer.

**Comment by cortho** [comment]
I'll check this.

Additionally a guest user should be able to create other guest users when the guests app is whitelisted?

**Comment by pmaier1** [comment]
> Additionally a guest user should be able to create other guest users when the guests app is whitelisted?

I don't think that guests should ever be able to create other guests. Was there another ticket on this or do I have a deja-vu?^^

**Comment by cortho** [comment]
Ok, thanks
Note: don't show guests when implementing https://github.com/owncloud/guests/issues/106
PS: I don't remember a similar ticket

**Comment by PVince81** [comment]
@pmaier1 move to "planned" or "development" ?

**Comment by cdamken** [comment]
> Additionally a guest user should be able to create other guest users when the guests app is whitelisted?

IMO Guest users should not be allowed to share, they are only to receive shares.

**Comment by PVince81** [comment]
How is a guest able to create another guest ? Currently their filesystem is setup so that resharing is not allowed as far as I remember. If not then let's make sure that permission mask set on their home storage removes the share permissions.

As for received shares, they should already have no share permission there IIRC.

@davitol steps to reproduce ?

**Comment by davitol** [comment]
> @davitol steps to reproduce ?

@PVince81 

With the current code the way that a guest user has to create another guest is adding guest app to the whitelist

**Comment by cortho** [comment]
@davitol this is not correct (any more). we needed to add guests to the default whitelisted apps (https://github.com/owncloud/guests/blob/master/lib/appwhitelist.php#L35) or else this route https://github.com/owncloud/guests/blob/ebc56266c87bdf4ffad8543e385c492a4b63d59c/js/guests.js#L80 would not be accessible.

**Comment by pmaier1** [comment]
> IMO Guest users should not be allowed to share, they are only to receive shares.

They are allowed to share when sharing permission is given. They are not allowed to invite additional guests.

**Comment by pmaier1** [comment]
Moved to planned for the version after the current one.

**Comment by davitol** [comment]
Current behaviour:

Guest user A seems to be allowed to share with Guest user B due to guest option appears in the sharing dropdown of the sidebar, even when the guest app is not included in the whitelist

![screen shot 2017-11-03 at 12 16 55](https://user-images.githubusercontent.com/10596560/32374499-503bff2c-c09e-11e7-81b6-ac699ad72182.png)


```
{"reqId":"HkMfxH8WepxhIYdppHFD","level":2,"time":"2017-11-03T11:19:56+00:00","remoteAddr":"85.57.168.79","user":"mymail@hotmail.com","app":"filesystem","method":"GET","url":"\/index.php\/apps\/files\/","message":"Storage wrapper 'oc_readonly' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems."}
{"reqId":"HkMfxH8WepxhIYdppHFD","level":3,"time":"2017-11-03T11:19:56+00:00","remoteAddr":"85.57.168.79","user":"mymail@hotmail.com","app":"index","method":"GET","url":"\/index.php\/apps\/files\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotPermittedException\",\"Message\":\"No create permission for folder \\\/avatars\\\/2d\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AvatarManager.php(99): OC\\\\Files\\\\Node\\\\Folder->newFolder('2d')\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AvatarManager.php(120): OC\\\\AvatarManager->getFolder(Object(OC\\\\Files\\\\Node\\\\Folder), '2d')\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AvatarManager.php(91): OC\\\\AvatarManager->getAvatarFolder(Object(OC\\\\User\\\\User))\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/TemplateLayout.php(101): OC\\\\AvatarManager->getAvatar('mymail@ho...')\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/template.php(232): OC\\\\TemplateLayout->__construct('user', 'files')\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(156): OC_Template->fetchPage()\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(112): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/base.php(928): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#12 \\\/opt\\\/owncloud\\\/index.php(56): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php\",\"Line\":162}"}
{"reqId":"4Z5SHiWG87HF8WYGUjlM","level":2,"time":"2017-11-03T11:19:57+00:00","remoteAddr":"85.57.168.79","user":"mymail@hotmail.com","app":"filesystem","method":"GET","url":"\/index.php\/apps\/files\/undefined\/img\/notifications.svg","message":"Storage wrapper 'oc_readonly' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems."}
```

**Comment by cortho** [comment]
@davitol fyi: guests app is whitelisted by default, see https://github.com/owncloud/guests/issues/114#issuecomment-337206981

**Comment by davitol** [comment]
@cortho And why it doesn't appear in the guest whitelist ?

**Comment by cortho** [comment]
This is, because I moved it to core whitelist:
https://github.com/owncloud/guests/blob/e21e28c9b11a6080948f0fededb83ad4ccc1830b/lib/appwhitelist.php#L35
which is always added but never shown.

**Comment by PVince81** [comment]
To play it safe I suggest the following approach:
- fix guest creation backend to refuse guest creation if initiated by guest user
- prevent loading guest app js code of autocomplete when logged in user is a guest

**Comment by davitol** [comment]
I'm agree with @PVince81 approach. @pmaier1 @cortho your opinion?

**Comment by pmaier1** [comment]
Yep, agree as well, sounds good! We should tackle this in the next iteration as it's an ugly thing that doesn't even work and has high probability to occur.

**Comment by cortho** [comment]
I like @PVince81 's approach too, which seems slim and only requires small code changes.

**Comment by PVince81** [comment]
Estimate: 0.5md including unit tests

**Comment by PVince81** [comment]
I've retried this, here are steps:

1. Login as "admin"
1. Create a user "user1"
1. Create a folder "test"
1. Share "test" with a new guest "example@example.org"
1. Set "can share" permissions for the share
1. Receive email, open link
1. Set a password
1. Login as "example@example.org"
1. Share "test" with "user1"
1. Share "test with a new guest "example2@example.org".

Now the thing I'm wondering: with what users should a guest be able to reshare ?
- local system users ?
- federated users ?
- new guests ?

If the answer of all these is **none**, then we should remove the "can share" permission and block sharing completely.

If we allow a subset of these, the fix will be different.

@pmaier1

**Comment by pmaier1** [comment]
> Now the thing I'm wondering: with what users should a guest be able to reshare ?

I think guests should just not be allowed to create guests (initial share with an unknown mail address). Sharing with existing guests should be allowed. Imagine a custom group consisting of externals (existing guests) and internals (local users) working on a project. All members of such group should be able to share with it. The externals should not be able to add other externals arbitrarily. 
If this is feasible, I'd give it a go. If a lot of effort, I'd defer and leave guest creation for guests open until there are actual complaints.

**Comment by PVince81** [comment]
There is a nuance to this: if the admin set the option "user can only share with members of same group" then yes you can make a custom group with guests seeing each others. However if the admin did not set that option it means any guest can share with any guest.

My worry is mostly about a guest being able to share with any other internal user and also arbitrary federated users.

**Comment by pmaier1** [comment]
> My worry is mostly about a guest being able to share with any other internal user and also arbitrary federated users.

Yes, this can be an issue under certain circumstances. For now I consider it as acceptable and the inviting user can remove the "can share" permission to prevent the guest from creating any shares if desired.

**Comment by PVince81** [comment]
Ok, so the agreement is as follows, with default sharing settings, a guest can share with any other users, groups, federated users and existing guests, but they can **not** share with new guests.

The fix needs to be done on both frontend and backend, whenever a user is logged in as guest:
- [ ] frontend: do not load JS file that extends the autocomplete with a guest entry
- [ ] backend: guest creation endpoint must return 403

**Comment by VicDeo** [comment]
@PVince81 
> Estimate: 0.5md including unit tests

considering that guests app has no unit tests but acceptance tests only? :)
