### ISSUE TITLE
Autocomplete in sharewizardtab does not work for guests group

### ISSUE THREAD

**Issue by davitol** [owncloud/guests#118]
Autocomplete should work as it happens with regular groups

![autocompletionfail](https://user-images.githubusercontent.com/10596560/28409060-ca6741d4-6d39-11e7-964d-2f3389902b1b.gif)

@cortho @pmaier1

**Comment by cortho** [comment]
Isn't this rather a general virtual group issue in core?

**Comment by pmaier1** [comment]
According to https://github.com/owncloud/guests/issues/122#issuecomment-317400512 this virtual group does not need to be found by autocompletion. This is expected behavior. Closing. Please reopen if I missed something!
