### ISSUE TITLE
GuestGroupName is not updated in shareviewTab

### ISSUE THREAD

**Issue by davitol** [owncloud/guests#119]
**Steps to reproduce**

1. In sharing menu, set a guestGroup name as **oldname**
2. In files view share a file/folder with the guestGroup
3. In sharing menu, modify guestGroup name as **newname**
4. In files view, check in the sharingTabview the groupname that appears is the **oldname** instead of the new one

**Comment by pmaier1** [comment]
I don't get the point of this :/ Can you elaborate a bit more or post a gif?

**Comment by cortho** [comment]
@davitol does this issue relate to https://github.com/owncloud/guests/issues/122?
If this is the case, I guess we can close this too.

**Comment by davitol** [comment]
![screen shot 2017-08-21 at 09 17 38](https://user-images.githubusercontent.com/10596560/29507828-1eb73614-8652-11e7-8a3d-92d163a52b9f.png)
![screen shot 2017-08-21 at 09 17 22](https://user-images.githubusercontent.com/10596560/29507837-2503ff48-8652-11e7-970c-8d5f8844e79d.png)
@pmaier1 @cortho I meant, if you share with guest group called 'invitados' and then in sharing menu you change the guest group name to 'Gast', in the files view sharetab it appears the old guest group name that no longer exists.

**Comment by pmaier1** [comment]
> and then in sharing menu you change the guest group name to 'Gast'

How can you change a group name in the sharing menu? Do you mean renaming the group in the guests settings?

**Comment by davitol** [comment]
Yes, I mean renaming it in sharing settings --> guest group name

**Comment by cortho** [comment]
Ok, I get it, but still not sure, if this is an issue, since we know from #122 that one never can share with a virtual group:

> https://github.com/owncloud/guests/issues/122#issuecomment-317400512 The design of the guests app did not include the possibility to share with all guests at once and I would question if this is necessary at all. The 'guests' group anyway is just a virtual group to determine guest status.

There are more open _virtual group_ issues, such as their display in the Users Panel https://github.com/owncloud/guests/issues/91

**Comment by davitol** [comment]
Agree, let's close the ticket
