### ISSUE TITLE
Trashbin icon for deleting groups should not be available for guests group in Users Page

### ISSUE THREAD

**Issue by davitol** [owncloud/guests#121]
![screen shot 2017-07-20 at 13 08 24](https://user-images.githubusercontent.com/10596560/28415215-0bf2cbb8-6d4f-11e7-84cd-0860d7b9de91.png)

@pmaier1 @cortho

**Comment by pmaier1** [comment]
Yes, good point!

**Comment by davitol** [comment]
Dupe of https://github.com/owncloud/guests/issues/45
