### ISSUE TITLE
Cannot share with guests group

### ISSUE THREAD

**Issue by davitol** [owncloud/guests#122]
Using PR https://github.com/owncloud/guests/pull/109

Cannot share with guests group.

![screen shot 2017-07-20 at 14 25 30](https://user-images.githubusercontent.com/10596560/28417366-353b52ac-6d58-11e7-9072-410607b47570.png)

**Steps to reproduce**

1. Share a file writing guests group in the SharetabView
2. Log in with a guest user that belongs to guests group

**Expected behavior**

The file should have been shared

**Current behavior**

The file does NOT appear in the guests user account

@pmaier1 FYI @cortho

**Comment by cortho** [comment]
I think this is the _virtual group_ issue as well (as in #118)
see  #91
I'm not very familiar with GroupBackends - is this an issue from implementing the GroupBackend or does it come from core?

**Comment by davitol** [comment]
@IljaN maybe can provide better info about this scenario

> I think this is the virtual group issue as well (as in #118 and #121)
> see #91
> I'm not very familiar with GroupBackends - is this an issue from implementing the GroupBackend or does it come from core?

**Comment by cortho** [comment]
after a first look it seems like we have to set correct values in the guests' group backend, isVisibleForScope. I cannot find valid values for scope, though ... investigating

**Comment by pmaier1** [comment]
The design of the guests app did not include the possibility to share with all guests at once and I would question if this is necessary at all. The 'guests' group anyway is just a virtual group to determine guest status. 

For now it is not necessary to be able to share with this group. If this comes up again it can be a feature request for the future.

Apart from that: An admin can offer the possibility to share with all guests by adding them to a second group. This is also scriptable by OCC or the provisioning API. I suggest to close here for now.

**Comment by cortho** [comment]
not a real issue now -> closing

**Comment by davitol** [comment]
Tested and works
