### ISSUE TITLE
Cannot save the changes of the whitelist features for guest pressing enter key

### ISSUE THREAD

**Issue by davitol** [owncloud/guests#125]
As in other browsers, it should be possible to save the changes of the whitelist features for guest pressing the enter key. For IE11 the way to save the changes is clicking away from the textbox.

@pmaier1 @cortho FYI

**Comment by pmaier1** [comment]
Yes, good point!

**Comment by cortho** [comment]
PR: https://github.com/owncloud/guests/pull/127

**Comment by cortho** [comment]
fixed with #127

**Comment by davitol** [comment]
Tested and works
