### ISSUE TITLE
Login as a guest is case sensitive

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/guests#133]
When trying to login as a guest, the username is case sensitive (unlike the general behavior of owncloud)

## steps to reproduce
1) create a guest account (i.e. username@owncloud.com)
2) try to login as `USERNAME@owncloud.com`

## actual behavior
Login fails

## expected behavior
Login is sucessfull

**Comment by pmaier1** [comment]
Yep, this is not the expected behavior. Needs to be fixed. Moving to 'planned' as the upcoming release in in code freeze phase.

**Comment by cortho** [comment]
login is NOT case sensitive with #109, so this will be fixed on the fly

**Comment by pmaier1** [comment]
> login is NOT case sensitive with #109, so this will be fixed on the fly

Great!
