### ISSUE TITLE
Adapt changelog

### ISSUE THREAD

**Issue by pmaier1** [owncloud/guests#140]
Please adapt the changelog in this repository.

- [x] Adapt CHANGELOG.md to the keepachangelog structure proposed and implemented by @PVince81 in core and e.g. https://github.com/owncloud/customgroups/blob/master/CHANGELOG.md

There's a script to compile the changelog according to merged PRs. For apps it could also be easier to note down changes manually.

Thanks a lot!

@PVince81

**Comment by pmaier1** [comment]
Assigning @cortho as he conducted all the recent changes.

**Comment by cortho** [comment]
PR: #141

**Comment by pmaier1** [comment]
This is done now, right? Closing. Please reopen if I missed something. Thanks!
