### ISSUE TITLE
Change license to GPLv2

### ISSUE THREAD

**Issue by pmaier1** [owncloud/guests#143]
- marketplace does not *yet* allow GPL
- is GPL an alllowed license for everybody of only selected publishers
- does CLA cover GPL? GPL is mirall only and AGPL is core (anyhow a bit unclear akak wrong - https://gist.github.com/DeepDiver1975/8ee1fb97bc7ea940e34bfdf10cfa46be)

Mainly @hodyroff has to answer this.

**Comment by pmaier1** [comment]
1. We allow GPL in the marketplace for everybody same as we do it with MIT/apache (review/approval needed)
2. Will check regarding CLA

**Comment by pmaier1** [comment]
Regarding CLA, @hodyroff committed to rework it to also apply to GPL.

**Comment by felixboehm** [comment]
done
