### ISSUE TITLE
Remove guest creation modal

### ISSUE THREAD

**Issue by pmaier1** [owncloud/guests#147]
Currently the modal that opens after clicking 'Add...' in the sharing dialog has only two purposes: Setting a user name and specifying an email address when just a name has been entered. We should give up this part of the feature in favor of making guest creation require one step less.

- Remove the ability to enter a user name for guest creation in favor of just entering mail addresses
- When address is not existing -> create guest
- When address is existing -> directly share internally (needs https://github.com/owncloud/guests/issues/115)

**Comment by cortho** [comment]
When the modal window would never come again we should remove the vue.js functionality as well.

@PVince81 do you recommend having the modal functionality still in the code (even when unused) or should we remove it along with the build process in the PR for this issue?

**Comment by PVince81** [comment]
If unused, just remove it with vue.js.

Thanks to git we can always resurrect it if needed in the future.

**Comment by cortho** [comment]
PR: https://github.com/owncloud/guests/pull/149

**Comment by felixboehm** [comment]
vue.js is the frontend framework and still needed, even without modal.

**Comment by cortho** [comment]
@felixboehm where is vue.js needed from the guests app context? Either I didn't find the occurrence or I just missed it. When looking at the 0.4.1 code I only see the modal using vue.js. Maybe @felixheidecke could help out too, as he introduced it back then.

**Comment by PVince81** [comment]
From what I saw and tested, vue.js isn't used anywhere any more.

If in the future we add UI elements that do need it, then we can add it back.
Not much point in keeping and shipping a library that is not used at all.

**Comment by pmaier1** [comment]
Can we close here?

**Comment by cortho** [comment]
yes.
