### ISSUE TITLE
Remove/Disable permission checkboxes if sharee is a guest

### ISSUE THREAD

**Issue by IljaN** [owncloud/guests#15]
also disallow sharing by guest users on the backend by checking inside a pre_share hook.

**Comment by IljaN** [comment]
Not needed after discussion with @pmaier1

**Comment by pmaier1** [comment]
Guest users should not be able to share with anyone. Therefore the checkboxes need to be greyed-out.

**Comment by PVince81** [comment]
Just make sure that when creating shares for guest users, they never receive the "share" permission, this will adjust the UI accordingly.

**Comment by PVince81** [comment]
This also means that if a guest users already exists and additional users share stuff with that user, they should not be able to give that user "share" permissions. (should be doable to remove the checkbox through the JS extension you guys made)

**Comment by pmaier1** [comment]
> This also means that if a guest users already exists and additional users share stuff with that user, they should not be able to give that user "share" permissions. (should be doable to remove the checkbox through the JS extension you guys made)

greying-out there as well is more effort than just removing it?

**Comment by PVince81** [comment]
Question: when sharing with guests, is this going through the regular OCS Share API ?
We need to prevent users to give guests share permissions also on OCS Share API level. Since these users are "regular" users in the system, then this API will allow sharing with them. Need to find a way to intercept the call and discard the share permission.

Or alternatively, allow storing the share permission in oc_share but filter it out after reading.

**Comment by PVince81** [comment]
> greying-out there as well is more effort than just removing it?

I think the checkbox is removed already when someone doesn't have share permissions. Just try removing share permissions of an outgoing share, then try resharing as recipient. You'll see how it looks like. From what I remember the checkbox is removed.

**Comment by pmaier1** [comment]
> I think the checkbox is removed already when someone doesn't have share permissions. Just try removing share permissions of an outgoing share, then try resharing as recipient. You'll see how it looks like. From what I remember the checkbox is removed.

Yes, confirmed. Identical behavior would be perfect.

![screenshot from 2017-03-21 10-28-48](https://cloud.githubusercontent.com/assets/21193500/24140706/444c028c-0e21-11e7-8713-989255001335.png)

**Comment by PVince81** [comment]
> Yes, confirmed. Identical behavior would be perfect.

It won't be identical, actually try it here instead https://github.com/owncloud/core/pull/27337 😉 
It will be indentical to that branch once merged.

Basically we only operate on backend level by disabling the existing "share" permission and triggering whatever behavior the UI has based on it.

**Comment by pmaier1** [comment]
So, this is on hold as we've still not agreed on the design of the guest user. We will hopefully come to a decision about it tomorrow.

**Comment by PVince81** [comment]
Just an additional note: for consistency if we need to remove the share checkbox also on mobile and desktop clients (these can also share with existing guests, but not create new guests), then we need to think of a solution about how to tell the clients about user types and pass that through the OCS Share API.

I don't like the user type approach but thought of another possibility: a "possible permissions for that user" field. Also to be passed along through the APIs. Then for guest users we need to remove the share permission from the possible permissions. Then web UI, mobile and desktop clients code need to be adjusted so they respect that setting when displaying their UIs.

**Comment by pmaier1** [comment]
Sharing will be allowed for guests just as for normal users. Closing here.
