### ISSUE TITLE
Mailhog should be part of tests/integration/run.sh

### ISSUE THREAD

**Issue by PVince81** [owncloud/guests#152]
@SergioBertolinSG we should start the mailhog docker from within the run.sh script. Goal is that anyone is able to run the tests locally with a single command.

**Comment by PVince81** [comment]
or if that's not acceptable, at least add a check in `run.sh` to see if port 8025 is reachable, if not, output an error message that tells how to start the mailhog docker.

**Comment by SergioBertolinSG** [comment]
Hmm maybe include a preparation script to download the mailhog image if it is not available and run the docker container?

**Comment by PVince81** [comment]
a separate script would be fine too and have the error message point to it.
I don't want to have to remember this complex docker command nor have to look it up in travis file every time

**Comment by patrickjahns** [comment]
This would be superseeded by being able to run `drone exec` ? Or is this still a requirement? then we could move the start/stop detection into run.sh and start a mailhog container if required

**Comment by PVince81** [comment]
requirement likely obsoleted by new CI infrastructure / drone
