### ISSUE TITLE
Travis fail with GuestsContext

### ISSUE THREAD

**Issue by PVince81** [owncloud/guests#153]
```
Class GuestsContext does not have a constructor, so you cannot pass any constructor arguments
```

when running tests on Travis. Works fine locally.

- [x] fix travis tests
- [ ] add travis badge in README

@SergioBertolinSG are you able to help here ?

**Comment by SergioBertolinSG** [comment]
This is the same problem as https://github.com/owncloud/customgroups/pull/110

**Comment by SergioBertolinSG** [comment]
This was fixed in https://github.com/owncloud/guests/pull/157
