### ISSUE TITLE
Update info.xml

### ISSUE THREAD

**Issue by pmaier1** [owncloud/guests#164]
- [x] Description (add new features, describe changed behavior -> only add via mail address)
- [x] Update screenshot (current one shows old behavior)

**Comment by pmaier1** [comment]
Description etc. is still correct and does not need changes for this release. With the next release we will add some more features which will bring up the need adaptation there.

As we dropped the creation model, however, the screenshot is out of date now and I don't know what we should show instead. The feature is only visible in the user share autocomplete and has a small section in admin settings.

@hurradieweltgehtunter can you provide a nice generic image for the guests app?

**Comment by hurradieweltgehtunter** [comment]
![owncloud-app-guests](https://user-images.githubusercontent.com/16665512/32442038-37f44970-c2fa-11e7-9406-8f693702f7c6.jpg)

pro/cons?

**Comment by hurradieweltgehtunter** [comment]
![owncloud-app-guests](https://user-images.githubusercontent.com/16665512/32442101-70813f0a-c2fa-11e7-976e-eb73561e13d6.jpg)

pro/cons?

**Comment by hurradieweltgehtunter** [comment]
![owncloud-app-guests](https://user-images.githubusercontent.com/16665512/32453526-b984b7a0-c31c-11e7-96e7-d5d76dc5ffb5.jpg)

**Comment by pmaier1** [comment]
PR for new screenshots https://github.com/owncloud/guests/pull/183

**Comment by pmaier1** [comment]
PR merged
