### ISSUE TITLE
Offer 'add as guest' only when a valid mail address is entered

### ISSUE THREAD

**Issue by pmaier1** [owncloud/guests#169]
I think the guests app autocomplete should only offer adding a user as a guest when a valid mail address (x@y.tld) is entered to guide users. See screenshot.

![screenshot from 2017-10-13 11-09-52](https://user-images.githubusercontent.com/21193500/31538958-6f2178ce-b007-11e7-8943-a5d06e184471.png)

What is a bit odd is that you immediately get to see the warning when no internal user is found while typing (see second screenshot). Not sure if we can somehow avoid this. Ideas?

![screenshot from 2017-10-13 11-11-53](https://user-images.githubusercontent.com/21193500/31538970-76364edc-b007-11e7-921d-8c96ffd9580c.png)

Edit: Screenshots were taken with the unreleased, 'modified' guests app (no modal etc.)

@PVince81 @cortho

**Comment by PVince81** [comment]
yeah, the current logic just detects the "@" sign, can be improved for sure.

> What is a bit odd is that you immediately get to see the warning when no internal user is found while typing (see second screenshot). Not sure if we can somehow avoid this. Ideas?

@pmaier1 core issue ? AFAIK it always behaved this way. Now if you say the behavior is different when guest app is enabled, then it's a bug in guest app.

**Comment by PVince81** [comment]
@cortho please take care of email validation. I thought we had some JS code for email validation elsewhere already but can't find it right now.

**Comment by pmaier1** [comment]
> Now if you say the behavior is different when guest app is enabled, then it's a bug in guest app.

No, that's core, right. Not sure about this one. We could leave it as it is but it might become even harder for people to recognize the guest feature because they might just stop typing when the "error" appears. Right now I can't really think of a nice way for improving this.. We could add a hint injected by the guests app somewhere in sharing dialog: e.g. "Just enter a mail address to invite guests"
Would need some more opinions on this.

**Comment by davitol** [comment]
> @cortho please take care of email validation. I thought we had some JS code for email validation elsewhere already but can't find it right now.

@PVince81 Do you refer to https://github.com/owncloud/guests/blob/master/controller/userscontroller.php#L103 ?

OOTH I opened that ticket related to different mail formats but finally I decided to close it https://github.com/owncloud/guests/issues/111

**Comment by PVince81** [comment]
No, the email detection must be done on the JS side. Because if whatever is entered is not a valid email, we should not insert the "Guest" entry in the dropbox.

**Comment by PVince81** [comment]
Of course we'll also need email validation on the server side at some point.

**Comment by cortho** [comment]
We do have server side email validation: https://github.com/owncloud/guests/blob/master/controller/userscontroller.php#L108
This issue is about client side validation, which has to be implemented

**Comment by cortho** [comment]
I'm going to prepare a PR today but I know I'll not make big friend with this. Since, for instance, a@a is a valid email address I will be only checking for this minimum pattern.

**Comment by pmaier1** [comment]
> Since, for instance, a@a is a valid email address

Even though you're probably right as it could be internal domains that are just like "x@localhost" I would like to be here a bit more strict and only allow addresses that are used in reality, meaning also require a top-level domain. Do you see any obstacles except that "internal" domains won't work?

**Comment by cortho** [comment]
Yes I see obstacles. When email addresses are valid per definitionem (=RFC) we cannot arbitrarily ignore them. IMHO we cannot dictate any user which domains he has to set up.

**Comment by pmaier1** [comment]
Ok, agree, you're right :+1:

**Comment by cortho** [comment]
@PVince81 looking at core or other apps I did not find a satisfying js check on email addresses. There is one check in core (https://github.com/owncloud/core/blob/f853d9b77e4747609707f5ef17818e46949c2361/core/js/sharedialogmailview.js#L87) which fails with any unicode character, maybe there is some other occurrence which I didn't find.

For this issue I didn't create or lookup any bloated regex which again might fail in some cases, especially as validation should be provided by core or any other library.

So this is the PR: https://github.com/owncloud/guests/pull/170

**Comment by PVince81** [comment]
In general I think this is not about strictness but only about UX. The goal is to only display the "add guest" entry when we detect something that looks like a valid email address, not any string containing an "@" sign. So if the email is valid as per RFC then we're good.
