### ISSUE TITLE
FR: make invite link timeout adjustable

### ISSUE THREAD

**Issue by dercorn** [owncloud/guests#184]
The duration until a password reset link expires is hard-coded. The default value does not accommodate for every users's needs.
Please make this adjustable.

**Comment by PVince81** [comment]
Should it be adjustable by the admin by setting a global value to something that makes more sense like maybe a week ? Or should every user be able to choose ?

**Comment by pmaier1** [comment]
I think that this goes beyond the border of things we want to make configurable unless it is a very hard requirement. If we don't have it yet we should find a nice default value and add a hint in the mail on how long the link will be valid.

**Comment by dercorn** [comment]
Since the whole basis of this FR was ill-advised, I will close it immediately.
