### ISSUE TITLE
Guest App not working in 10.0.3 when Enterprise Theme App is enabled

### ISSUE THREAD

**Issue by haukman** [owncloud/guests#187]
Steps to reproduce:

1. Install an ownCloud Enteprise Version 10.0.3 (Enterprise Theme enabled)
2. Configure email
3. Install Guest app
4. Try to share/create a guest

Expected behaviour:
Should be able to create a guest in sharing dialog.

Actual behaviour:
Not possible to create a guest, only federated share:

![grafik](https://user-images.githubusercontent.com/25486818/35382071-78bef114-01be-11e8-8a67-334220743190.png)

As soon as I disable the the Enterprise Theme App, the guest feature is visible again:

![grafik](https://user-images.githubusercontent.com/25486818/35381934-1570a116-01be-11e8-92dd-4c5f3b279942.png)

Can see this in the Logs:

`{"reqId":"R0DQsW5zEcaUERgKvKX5","level":1,"time":"2018-01-25T09:54:50+00:00","remoteAddr":"192.168.48.5","user":"admin","app":"theme-enterprise","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php","message":"user <admin>, displayName <admin> enabled app \"theme-enterprise\" [CLIENT_IP: 192.168.48.5] [USER_AGENT: Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko\/20100101 Firefox\/57.0]"}
{"reqId":"olHSwJpT9EBCKbIuuAlT","level":3,"time":"2018-01-25T09:54:50+00:00","remoteAddr":"192.168.48.5","user":"admin","app":"PHP","method":"GET","url":"\/apps\/files","message":"include(layout.noscript.warning.php): failed to open stream: No such file or directory at \/var\/www\/owncloud\/apps\/theme-enterprise\/core\/templates\/layout.user.php#36"}
{"reqId":"olHSwJpT9EBCKbIuuAlT","level":3,"time":"2018-01-25T09:54:50+00:00","remoteAddr":"192.168.48.5","user":"admin","app":"PHP","method":"GET","url":"\/apps\/files","message":"include(): Failed opening 'layout.noscript.warning.php' for inclusion (include_path='\/var\/www\/owncloud\/apps:\/var\/www\/owncloud\/custom') at \/var\/www\/owncloud\/apps\/theme-enterprise\/core\/templates\/layout.user.php#36"}
{"reqId":"NnEISwvY0DcBfMlzsLFj","level":3,"time":"2018-01-25T09:54:51+00:00","remoteAddr":"192.168.48.5","user":"admin","app":"PHP","method":"GET","url":"\/apps\/files\/","message":"include(layout.noscript.warning.php): failed to open stream: No such file or directory at \/var\/www\/owncloud\/apps\/theme-enterprise\/core\/templates\/layout.user.php#36"}
{"reqId":"NnEISwvY0DcBfMlzsLFj","level":3,"time":"2018-01-25T09:54:51+00:00","remoteAddr":"192.168.48.5","user":"admin","app":"PHP","method":"GET","url":"\/apps\/files\/","message":"include(): Failed opening 'layout.noscript.warning.php' for inclusion (include_path='\/var\/www\/owncloud\/apps:\/var\/www\/owncloud\/custom') at \/var\/www\/owncloud\/apps\/theme-enterprise\/core\/templates\/layout.user.php#36"}
{"reqId":"Hi1ZpHUN1K053YcYfeLp","level":1,"time":"2018-01-25T09:55:10+00:00","remoteAddr":"","user":"--","app":"cron","method":"--","url":"--","message":"Invalidating tokens older than 2018-01-24T09:55:10+00:00"}
{"reqId":"OGiNL4EyoaeXaLpsZZEg","level":1,"time":"2018-01-25T09:56:10+00:00","remoteAddr":"","user":"--","app":"cron","method":"--","url":"--","message":"Invalidating tokens older than 2018-01-24T09:56:10+00:00"}
{"reqId":"nY8Es9P8F52DhhUA8zz0","level":1,"time":"2018-01-25T09:57:13+00:00","remoteAddr":"","user":"--","app":"cron","method":"--","url":"--","message":"Invalidating tokens older than 2018-01-24T09:57:13+00:00"}
{"reqId":"r5yEJZLLDWEBwm9swsfY","level":3,"time":"2018-01-25T09:57:34+00:00","remoteAddr":"192.168.48.5","user":"admin","app":"PHP","method":"GET","url":"\/settings\/personal","message":"include(layout.noscript.warning.php): failed to open stream: No such file or directory at \/var\/www\/owncloud\/apps\/theme-enterprise\/core\/templates\/layout.user.php#36"}
{"reqId":"r5yEJZLLDWEBwm9swsfY","level":3,"time":"2018-01-25T09:57:34+00:00","remoteAddr":"192.168.48.5","user":"admin","app":"PHP","method":"GET","url":"\/settings\/personal","message":"include(): Failed opening 'layout.noscript.warning.php' for inclusion (include_path='\/var\/www\/owncloud\/apps:\/var\/www\/owncloud\/custom') at \/var\/www\/owncloud\/apps\/theme-enterprise\/core\/templates\/layout.user.php#36"}
{"reqId":"2gs0tf3evmCOlGZiT7fd","level":3,"time":"2018-01-25T09:57:37+00:00","remoteAddr":"192.168.48.5","user":"admin","app":"PHP","method":"GET","url":"\/settings\/admin?sectionid=general","message":"opendir(\/var\/www\/owncloud\/themes): failed to open dir: No such file or directory at \/var\/www\/owncloud\/apps\/templateeditor\/lib\/mailtemplate.php#155"}
{"reqId":"2gs0tf3evmCOlGZiT7fd","level":3,"time":"2018-01-25T09:57:37+00:00","remoteAddr":"192.168.48.5","user":"admin","app":"PHP","method":"GET","url":"\/settings\/admin?sectionid=general","message":"include(layout.noscript.warning.php): failed to open stream: No such file or directory at \/var\/www\/owncloud\/apps\/theme-enterprise\/core\/templates\/layout.user.php#36"}
{"reqId":"2gs0tf3evmCOlGZiT7fd","level":3,"time":"2018-01-25T09:57:37+00:00","remoteAddr":"192.168.48.5","user":"admin","app":"PHP","method":"GET","url":"\/settings\/admin?sectionid=general","message":"include(): Failed opening 'layout.noscript.warning.php' for inclusion (include_path='\/var\/www\/owncloud\/apps:\/var\/www\/owncloud\/custom') at \/var\/www\/owncloud\/apps\/theme-enterprise\/core\/templates\/layout.user.php#36"}
`

**Comment by pmaier1** [comment]
Thanks for opening the issue and providing detailed information. AFAIK it works with 10.0.4 and later versions so not critical. Anyway we should understand the issue and research on reasoning.

**Comment by cortho** [comment]
At a first glance this looks more like an Enterprise Theme issue than a guest app one, especially when I look at the log entries.

**Comment by PVince81** [comment]
Would also be good to know what version of the enterprise theme they got. It is possible that we updated it in the marketplace and am not sure whether we tested the newest version together with 10.0.3.

**Comment by glannes31** [comment]
Hello , and for this message?{"reqId":"2gs0tf3evmCOlGZiT7fd","level":3,"time":"2018-01-25T09:57:37+00:00","remoteAddr":"192.168.48.5","user":"admin","app":"PHP","method":"GET","url":"\/settings\/admin?sectionid=general","message":"include(): Failed opening 'layout.noscript.warning.php' for inclusion (include_path='\/var\/www\/owncloud\/apps:\/var\/www\/owncloud\/custom') at \/var\/www\/owncloud\/apps\/theme-enterprise\/core\/templates\/layout.user.php#36"}

layout.noscript.warning.php must be in the custom theme?

**Comment by PVince81** [comment]
@VicDeo ^

**Comment by VicDeo** [comment]
https://github.com/owncloud/theme-enterprise/issues/9
https://github.com/owncloud/theme-enterprise/pull/10

**Comment by glannes31** [comment]
And for the person can t see your links ? I have z 404 error

Envoyé depuis Yahoo Mail pour Android 
 
  Le mer., févr. 21, 2018 à 17:05, Viktar Dubiniuk<notifications@github.com> a écrit :   
owncloud/theme-enterprise#9
owncloud/theme-enterprise#10

**Comment by VicDeo** [comment]
Fixed in theme-enterprise 2.0.1
