### ISSUE TITLE
ownCloud app on android not working with guest account

### ISSUE THREAD

**Issue by oradke** [owncloud/guests#196]
Hi all!
I have noticed that the android ownCloud app does not show any files when logging in as a guest user. Log files show a WebDAV error - might be related to the problem of having the @ character in the username. ownCloud app on iOS works fine though.

Can anyone with deeper insight confirm this?

Thanks!
Oliver

**Comment by oradke** [comment]
Error message in log: 
`"Storage wrapper 'oc_readonly' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems."`

**Comment by davitol** [comment]
Tested with ownCloud 10.0.10 latest android owncloud app and works for me. I was able to log into the guest account. Does it keep failing for you?

**Comment by PVince81** [comment]
please reopen if the issue still happens and use the issue template: https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md
