### ISSUE TITLE
Expand acceptance testing for uploads

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/guests#216]
With https://github.com/owncloud/guests/pull/212 we already included some basic chunked upload testing.

However, this only uses a specific stile of chunking. As ownCloud currently supports chunking v1 and v2 - we need to expand the test cases to cover both upload parts

**Comment by patrickjahns** [comment]
To be discussed:
- Minimal UI testing of uploading a large file (> 10MB) via selenium?

**Comment by individual-it** [comment]
this need also be done for #278 so adding it to the current sprint
