### ISSUE TITLE
Guests cannot browse back to files view when they are in settings menu

### ISSUE THREAD

**Issue by davitol** [owncloud/guests#220]
![screen shot 2018-06-13 at 13 48 46](https://user-images.githubusercontent.com/10596560/41349672-e7f49d6c-6f10-11e8-9235-c591e766fe5e.png)

Files Folder is not listed when clicking on settings page

**Comment by PVince81** [comment]
always ? did you modify whitelist ?

**Comment by davitol** [comment]
> always ? did you modify whitelist ?

No, i didn't

**Comment by davitol** [comment]
> @davitol mind checking if this is a regression ?

regresion, works with guest 0.4.2

**Comment by PVince81** [comment]
ok, I think we should look at this before releasing another guest app

**Comment by PVince81** [comment]
Works for me if activity app is enabled also.

This is a core bug: whenever there is only one entry (the files app), the menu is disabled. This works fine when one is already in the files app but not when in the settings app.

Let's keep this ticket anyway.

**Comment by PVince81** [comment]
Looks like the guest app contains special handling that removes the navigation menu whenever the menu only contains a single item. This is wrong:

1) if we want to hide the menu when it only contains one item, it's the responsibility of core to do that, not an app

2) the code in question doesn't take the current view into account

As a fix, I'm going to remove this particular part of code so the menu will always expand.
If we do want to hide the menu when there's only a single entry, we'll need to do so in core.

@pmaier1 FYI

**Comment by cortho** [comment]
@PVince81 IIRC this was introduced to be able to remove non-whitelisted apps from the menu (before clicking on a non-whitelisted app resulted in some "access to resource denied" error). So _that_ functionality must be handled by the app.

Still it might be questionalble, if https://github.com/owncloud/guests/blob/e8ecdd356ddb2337878a37ebb9328e1d812921d1/js/navigation.js#L42 is the correct answer for hiding the _files_ entry.

**Comment by PVince81** [comment]
yes, this is the line I've removed

PR here: https://github.com/owncloud/guests/pull/221
