### ISSUE TITLE
Code review for first version

### ISSUE THREAD

**Issue by PVince81** [owncloud/guests#23]
@IljaN @felixheidecke placeholder ticket for the code review once you guys are done or close to completion. After this, all future PRs will need direct reviews.

The current process is only to save you guys a bit of time and avoid having one gigantic PR with all changes.

Please ping here when ready.

**Comment by PVince81** [comment]
@ineumann 

- [ ] are we sure the user is always non-null here ? https://github.com/owncloud/guests/blob/master/lib/hooks.php#L197
- [ ] double check whether the password reset email as used here will still work after this PR is merged: https://github.com/owncloud/core/pull/27277 (that one introduces another part inside the token)
- [ ] optional: it should be possible to build a permalink here which is much simpler: https://github.com/owncloud/guests/blob/master/lib/mail.php#L126. You need to find the fileid then append it to the URL: `http://example.org/owncloud/f/$fileId`
- [ ] need a proper solution to get rid of this hard-coded stuff: https://github.com/owncloud/guests/blob/master/appinfo/app.php#L26
- [ ] whitelist not implemented ? get rid of it for now ? https://github.com/owncloud/guests/blob/master/appinfo/app.php#L41
- [ ] database.xml ? I thought we didn't want to have a list of guests in the app, maybe it's unused and must be deleted ?
- [ ] appinfo/info.xml:
    - [ ] adjust license https://github.com/owncloud/guests/blob/master/appinfo/info.xml#L8
- [ ] use the new settings registration way https://github.com/owncloud/guests/blob/master/settings/admin.php#L24

@felixheidecke 

- [ ] please use more specific selector here: https://github.com/owncloud/guests/blob/master/js/app.js#L253, maybe `obj.$el.find('.shareWithField')`

**Comment by IljaN** [comment]
@PVince81 I think we can remove this one completly, I think ldap won`t matter in the current implementation.
https://github.com/owncloud/guests/blob/master/appinfo/app.php#L26

**Comment by IljaN** [comment]
Reimplemented app whitelisting: https://github.com/owncloud/guests/commit/3e2b78f16f29855c7805247f61f1887cb29823e5
