### ISSUE TITLE
Use ShareManager for getItemSharedWithUser

### ISSUE THREAD

**Issue by PVince81** [owncloud/guests#235]
:warning: prerequisite for the app to work on OC 11

**Comment by PVince81** [comment]
Instead of hacking around the old hook, might be better to listen to the new Symfony event which already provides the matching IShare object.

As I see, the current code is not using all the passed info and is using `getItemSharedWithUser()` to re-get the share in question.

**Comment by VicDeo** [comment]
Require min-version bump to 10.0.8  https://github.com/owncloud/core/pull/31026

**Comment by PVince81** [comment]
that's fine I think

**Comment by VicDeo** [comment]
PR is here https://github.com/owncloud/guests/pull/245
