### ISSUE TITLE
user autofocus can be null

### ISSUE THREAD

**Issue by PVince81** [owncloud/guests#236]
Scenario is not clear, this was observed in a log:
```
ErrorException: Undefined index: user_autofocus
#11 guests/templates/form.password.php(42): handleError
#10 guests/templates/form.password.php(42): include
#9 /var/www/owncloud/lib/private/Template/Base.php(219): load
#8 /var/www/owncloud/lib/private/Template/Base.php(194): fetchPage
#7 /var/www/owncloud/lib/private/legacy/template.php(236): fetchPage
#6 /var/www/owncloud/lib/public/AppFramework/Http/TemplateResponse.php(149): render
#5 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(108): dispatch
#4 /var/www/owncloud/lib/private/AppFramework/App.php(100): main
#3 /var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(46): __invoke
#2 /var/www/owncloud/lib/private/Route/Router.php(342): match
#1 /var/www/owncloud/lib/base.php(909): handleRequest
#0 /var/www/owncloud/index.php(54): null
```

**Comment by mrlinux1** [comment]
I got the same error with a customer:

owncloud.log:
User opens password page for guests app:
 {"reqId":"W7yiEz@ssb1CklHMdYUtxAAAAAM","level":3,"time":"2018-10-09T14:41:55+02:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"--","app":"PHP","method":"GET","url":"\/index.php\/apps\/guests\/register\/XXXXXXXXXXXXXXXXXXXXXX","message":"Undefined index: user_autofocus at \/var\/www\/owncloud\/apps\/guests\/templates\/form.password.php#42"}

apache.log
User clicks submit button:

 Benutzer bestätigt submit button der Form:
XXX.XXX.XXX.XXX - "" [09/Oct/2018:14:43:33 +0200] "GET /index.php/apps/guests/register HTTP/1.1" 405 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Safari/605.1.15”

owncloud 10.0.9.5 with guests app 0.5.0

**Comment by PVince81** [comment]
I've grepped the code and it seems it is **always** null as there is no code that seems to set it.

Either we deleted some important code or this is obsolete. Needs further research.

Automatically focussing on the password field on the guest password page is certainly desirable.

**Comment by PVince81** [comment]
linked ticket said that this is a regression from 10.0.8, see https://github.com/owncloud/guests/issues/225

**Comment by PVince81** [comment]
it is possible that this attribute used to be set by core.
