### ISSUE TITLE
Add build script

### ISSUE THREAD

**Issue by PVince81** [owncloud/guests#24]
Like a Makefile where `make dist` builds the app into "build/guests/" and strips all unwanted files.

See https://github.com/owncloud/customgroups/blob/master/Makefile for an example, it has sub-rules-files.
I hope to make this reusable for apps eventually.

**Comment by PVince81** [comment]
@felixheidecke is this app still using LESS/SASS ? We can't rely on people using specific IDEs to build this app especially if we want to automate this at some point.

**Comment by felixheidecke** [comment]
Nope … no pre-compilers at this point.

**Comment by PVince81** [comment]
maybe reuse the makefile from the market app

**Comment by PVince81** [comment]
Can we have a makefile here ? Checking out the app alone doesn't seem to be enough to make it work and I always forget those `npm run build` commands...

**Comment by felixheidecke** [comment]
Well … I'll read into makefiles then :-)

**Comment by pmaier1** [comment]
@cortho will take care, right?

**Comment by cortho** [comment]
PR: #137
