### ISSUE TITLE
Investigate acceptance test failure

### ISSUE THREAD

**Issue by PVince81** [owncloud/guests#247]
See failure in https://github.com/owncloud/guests/pull/244

@phil-davis FYI, for next sprint

**Comment by PVince81** [comment]
seems it went away

**Comment by PVince81** [comment]
still failing https://drone.owncloud.com/owncloud/guests/233

**Comment by phil-davis** [comment]
Fixed in PR #249 
(that does not explain everything, but at least gets CI up to "modern" style and it passes)
