### ISSUE TITLE
Extending sharedialogview.js

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/guests#3]
Extending OCA.Share using OC.Plugins.register('OCA.Share… does not work as expected.

- https://github.com/owncloud/guests/commit/b77ecfb46152088342c7be5da0743499e0c77f57
- https://github.com/owncloud/core/commit/3f867942623bcbebbb83bf8884808a9fe5634722

Registering the plugin does indeed work, but overriding an existing methods apparently does not take place. (Add a breakpoint [HERE](https://github.com/owncloud/guests/blob/b77ecfb46152088342c7be5da0743499e0c77f57/js/app.js#L3) to see the results)

**Comment by PVince81** [comment]
Try moving the attach method to the class constructor.
Currently it's directly inside the autocompleteHandler which you are also trying to override within the plugin. It cannot work because you're trying to replace the function you are already in.

**Comment by felixheidecke** [comment]
I tried to put it in so many places. The problem might be, that my desired object does some backbone view extending: https://github.com/owncloud/core/blob/3f867942623bcbebbb83bf8884808a9fe5634722/core/js/sharedialogview.js#L47

**Comment by PVince81** [comment]
It doesn't matter.

Can you put this all in PRs so I can try it out ? (a PR for the core change and a PR for the guests app)

**Comment by felixheidecke** [comment]
@PVince81 
https://github.com/owncloud/core/pull/27253
https://github.com/owncloud/guests/pull/5

**Comment by felixheidecke** [comment]
Worked fine :-)
