### ISSUE TITLE
[Strictly 10.3.0] Guest 0.8.2

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/guests#338]
### Reason

- [x] https://github.com/owncloud/guests/pull/337 to align sharing ui

### QA

- [x] Create **QA Milestone** @davitol 
- [x] Move items from `development` to `qa` @davitol 
- [x] Create release branch with the format "release-$version" @patrickjahns 
- [x] Create "0.8.2 Testplan" @davitol https://github.com/owncloud/guests/issues/349

### Documentation

- [ ] Changes in the docs needed?

### Marketing

- [x] Ping @owncloud/marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix) @davitol 
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown) @davitol 

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch  @patrickjahns 
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build) @patrickjahns 
- [x] Upload as Github release using changelog entries @patrickjahns 
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch @davitol https://github.com/owncloud/guests/issues/349

#### Final

- [x] Create github tag for final 'v${version}' on release branch @patrickjahns 
- [x] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build) @patrickjahns 
- [x] Upload as Github release using changelog entries @patrickjahns 
- [x] Smoke test tarball (at least install + enable) @patrickjahns 

### Publishing

- [x] Upload tarball to marketplace (see handbook for details) @patrickjahns 
- [x] Publish tarball for customers (see handbook for details) @patrickjahns 
- [ ] Send mail to release-coordination with link to this ticket and to the changelog @patrickjahns 

### Post-release

- [x] Rename QA milestone to '$version' @patrickjahns 
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01) @patrickjahns 
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number @patrickjahns

**Comment by davitol** [comment]
Tarball is QA ready:

Issues found while testing: https://github.com/owncloud/guests/issues/349#issuecomment-518699693
