### ISSUE TITLE
Enable the admin to detect guest accounts with no shares left

### ISSUE THREAD

**Issue by pmaier1** [owncloud/guests#34]
It should be possible for an admin to get a list of guest users who have no shares so that the admin can decide to delete these manually after a while.

Requirement:
- [ ] Admin (suppose he has shell access) should be able to get a list of guests that have no shares left to manually/automatically delete those

Ideas how to do this
- Config report
- OCC command
- Indicator/filter in UI

I'm in favor of OCC as it would be scriptable. What do you think?

**Comment by PVince81** [comment]
In theory the occ command could simply be part of the guest app.

- "occ guests:list": list all guests including info whether they have shares or not
- "occ guests:list --noshares" same as above but limit to ones that have no share

@IljaN

**Comment by pmaier1** [comment]
closing in favor of https://github.com/owncloud/guests/issues/110
