### ISSUE TITLE
Modify default apps whitelist for guest users deleting 

### ISSUE THREAD

**Issue by davitol** [owncloud/guests#350]
Due to new guest app version 0.8.2 is for oC 10.3, and due to Gallery is no longer supported , we must update the default apps whitelist

![Screen Shot 2019-08-06 at 14 51 23](https://user-images.githubusercontent.com/10596560/62541239-b59bd680-b859-11e9-8bb0-791e6a5e063a.png)

@pmaier Feedback?

**Comment by patrickjahns** [comment]
Other thought here, to include `files_mediaviewer` but leave gallery and video_player for legacy setups which cant yet migrate to mediaviewer

**Comment by pmaier1** [comment]
Good catch @davitol, thanks a lot!

> Other thought here, to include files_mediaviewer but leave gallery and video_player for legacy setups which cant yet migrate to mediaviewer

Yes, I agree with this. It doesn't hurt to keep them in there for legacy reasons. Please just add `files_mediaviewer`.

**Comment by patrickjahns** [comment]
Fixed in https://github.com/owncloud/guests/pull/315
