### ISSUE TITLE
Enable guests tests with core tarball when 10.3 is available

### ISSUE THREAD

**Issue by phil-davis** [owncloud/guests#358]
The tests against core 10.2.1 tarball were commented out by https://github.com/owncloud/guests/pull/354/commits/0910e2923d08e787e8a56b25441e709cb34d7111 because the new guests 0.8.2 requires core 10.3

When 10.3.0 tarballs are available, revert that commit and run the tests against 10.3.0

**Comment by sharidas** [comment]
The change is merged: https://github.com/owncloud/guests/pull/359. Hence closing this issue.
