### ISSUE TITLE
Data migration from old guest app to new guest app

### ISSUE THREAD

**Issue by IljaN** [owncloud/guests#37]
Convert all users from the old guests table to normal users which match the following criteria:
- Member of previously configured guest group (if previously enabled)
- All users with quota 0 (if previously enabled)
- Guest by contact ??? (if previously enabled)

Technically users  need to be moved from table oc_guests to oc_users and receive the flag "isGuest=1" inside oc_preferences table.
The old guest app table has the e-mail address as uid so there shouldn`t be any collisions.

Open questions:
- Possibility to migrate shares?

**Comment by IljaN** [comment]
@PVince81 More toughts on this?

/cc @felixboehm

**Comment by PVince81** [comment]
cc @butonic

**Comment by PVince81** [comment]
Now I feel a bit sad that we decided against keeping that table and creating users directly in core instead of keeping what is there. But maybe I should have looked at the code more deeply before deciding, oh well.

About migrating shares: if the uid is exactly the same after migration then you don't need to adjust anything, the old shares will be pointing to the same email/uid as before.

**Comment by IljaN** [comment]
> Now I feel a bit sad that we decided against keeping that table and creating users directly in core instead >of keeping what is there. But maybe I should have looked at the code more deeply before deciding, oh >well.

I still think it was the right decision. There is a saying in software engineering akin to "Special cases are the cause of bad software (architecture)". So even if we need to walk the extra mile now, we got rid of a special case. :tada:

**Comment by PVince81** [comment]
Hmm, I rather see having an app writing directly into the core stuff a special case while having a user backend that speaks our API language be not that special.

**Comment by IljaN** [comment]
Also true... :thinking:

**Comment by felixboehm** [comment]
The data representation is not important for a migration. We need an API for managing Guests and then a migration can be done with a small script. 
Planned for 10.0.4.

**Comment by PVince81** [comment]
@IljaN can you estimate effort for writing an occ command for a migration of the old data ?

I don't think we want this as a "DB style migration" at this point since the app was released already and there is a risk of false positives in case admins used the "guest" group for something else.

**Comment by IljaN** [comment]
AFAIR the old guest app was using a custom table for guest users, so these would need to be migrated in to oc_users + oc_accounts, then isGuest=1 flag needs to be set in oc_preferences on each users.

About shares I need to dig deeper, since they would need rewiring to the new uids in oc_users/oc_storage

**Comment by IljaN** [comment]
Here is guest_app in old state: https://github.com/owncloud/guests/tree/31b2440d049d2cb851d0382a312172253d1e6db2

**Comment by IljaN** [comment]
Tasks:
- Read old guest table via sql and convert the users to normal users in oc_users/oc_accounts using user-manager 
- Remap share_with in oc_shares to new uid's (if required)
- Set isGuest=1 on each user in oc_preferences;

~3-5md

@PVince81 Anything I am missing?

**Comment by PVince81** [comment]
I think remapping shares isn't needed at all as the user ids should be the same as before.

We need to think about what to do if the target user id already exists. Maybe the user already got migrated manually in that case.

**Comment by PVince81** [comment]
If remapping was involved, it's way more than just the shares: there could be other metadata like comments, activity, etc to migrate. Unless we agree to discard those.

For a simple solution I'd rather focus on keeping the user ids the same.

**Comment by IljaN** [comment]
If shares etc. can stay the same then probably ~2-3 md

**Comment by IljaN** [comment]
@PVince81 the old guest app used email addresses as uid, do we support this in oc_users?

**Comment by IljaN** [comment]
Also we need to check if the hash (password) is compatible to the password hash we use in oc_users. Guest app is using hasher service (IHasher)

**Comment by PVince81** [comment]
@butonic in the current implementation users are in oc_users and have a flag "isGuest".
We're only talking about migrating the users, not rewriting the guests app again.

**Comment by PVince81** [comment]
> No idea what needs to go where.

see https://github.com/owncloud/guests/issues/37#issuecomment-405629109

**Comment by PVince81** [comment]
> the old guest app used email addresses as uid, do we support this in oc_users?

@IljaN yes we do.

**Comment by pmaier1** [comment]
The new guests app is available for a long time now and remaining old installations are migrated manually. We'll not invest time in this anymore as part of the new guests app. Closing.
