### ISSUE TITLE
API acceptance tests do not work nicely for guest users with uppercase in the email

### ISSUE THREAD

**Issue by phil-davis** [owncloud/guests#395]
The webUI test scenarios work fine for guest email addresses that contain uppercase, e.g. `John.Smith@example.com`

But the API test scenarios use code that tries to simulate what the webUI calls that are made to the guests app "private" API. The test code needs to be smarter about exactly when the upper or lower case version of the username/email-address needs to be put in various API calls and checked in responses.

e.g. in `apiGuests/guests.feature` replace `john.smith` with `John.Smith` - then sort out the test code so the tests pass.

**Comment by kiranparajuli589** [comment]
> The webUI test scenarios work fine for guest email addresses that contain uppercase, e.g. `John.Smith@example.com`

@phil-davis IMO every guest emails are converted to lowercase during creation..
Our webUI test works fine because we also imitate naming convention using function `prepareUserNameAsFrontend` which lowers any upper-cased alphabets containing inside provided mail address and then continues to guest user creation

> But the API test scenarios use code that tries to simulate what the webUI calls that are made to the guests app "private" API. The test code needs to be smarter about exactly when the upper or lower case version of the username/email-address needs to be put in various API calls and checked in responses.

converting emails into lower-case may be bug or a feature,

**Comment by kiranparajuli589** [comment]
Trying locally, when we create guest users with upper-cased email address:
![Screenshot from 2020-03-05 15-18-48](https://user-images.githubusercontent.com/39373750/75967983-c34f3280-5ef4-11ea-8c3e-e62a098c7e52.png)
- `username` is set to `lower-cased` mail address
- `email addr` is as we provided
- `fullName` email we provided
