### ISSUE TITLE
guests 0.9.0

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/guests#397]
### Reason

- [x] https://github.com/owncloud/guests/pull/384
- [x] https://github.com/owncloud/guests/pull/393

### QA

- [x] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "0.8.3 Testplan" @davitol https://github.com/owncloud/guests/issues/400#issuecomment-599860752 
 
### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [x] Ping @owncloud/marketing
- [x] Ping pmaier to check `info.xml` description and screenshot

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) @davitol https://github.com/owncloud/guests/issues/400

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Rename QA milestone to `$version`
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [x] Close the milestone
- [x] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date

**Comment by HanaGemela** [comment]
@davitol RC1 available in https://github.com/owncloud/guests/releases/tag/v0.8.3RC1

**Comment by davitol** [comment]
@HanaGemela Changelog item says only `Bump libraries`

I think we should make it clearer and Say something like `Bump handlebars from 4.1.1 to 4.7.3` `https://github.com/owncloud/guests/pull/393`

**Comment by davitol** [comment]
> @davitol RC1 available in https://github.com/owncloud/guests/releases/tag/v0.8.3RC1

@HanaGemela Tarball is QA-ready

Details to take into account:

- Modify Changelog in order to give more details: https://github.com/owncloud/guests/issues/397#issuecomment-599719938

- As commented in https://github.com/owncloud/guests/issues/400#issuecomment-599860752 we maybe have to set min-version to 10.4

**Comment by HanaGemela** [comment]
Server version has been increased so instead of a patch release this has to be a minor release
I've build 0.9.0RC1 https://github.com/owncloud/guests/releases/tag/v0.9.0RC1

@davitol please test. Previous branch has been merged back to master and a new branch has been created from master. The changes are: min server version bump, updated changelog and test dependencies. I suggest a smoke test

**Comment by davitol** [comment]
@HanaGemela Tested and LGTM. 🚢 it

> https://github.com/owncloud/guests/releases/tag/v0.9.0RC1
