### ISSUE TITLE
Tracking Testing results for Guests 0.9.0 RC1

### ISSUE THREAD

**Issue by davitol** [owncloud/guests#400]
Tested in ownCloud 10.4 and using the tarball provided here: https://github.com/owncloud/guests/releases/tag/v0.8.3RC1
## 'Guest App' Test Plan

- Run Testplan with encryption enabled

## Testing functionality

Test Case | Expected Result | Result | Related Comment
------------- | -------------- | ----- | ------
**CLI commands** |  |   |
|  |   |
Enable Guest app via CLI using ```occ app:enable guests``` | The apps is enabled | ✅   |
Disable Guest app via CLI using ```occ app:disable guests``` | The apps is disabled | ✅  |
**Add Guest User in sharetabview** |  |   |
|  |   |
Create a guest user via email |  | ✅ |
Try to create a guest user via email sharing from another guest user |  | ✅  | Guest user is not created
Create a guest user via email sharing from an LDAP user |  | ✅ |
Create a guest user via email sharing from an Shibboleth user | | :construction:  |
Try to create a guest user via email when a server email is not set or it is invalid|  Guest user option does not appear | ✅ |
Try to create a guest user via email with an invalid email format | Guest user option does not appear | ✅  |
Try to create a guest user via email with an already used email | Guest user should appear as User. Cannot create another guest user | ✅  |
Try to create a guest user via email already registered by email |  Guest user should appear as User. Cannot create another guest user | ✅  |
Create a guest user via email using a password that fits password policy | Check that the user receives the email and can register into oC | ✅  | 
Create a guest user via email using a password that doesn't fit password policy | Check that the user receives the email and cannot register into oC. A warning related to password policy should be shown | ✅  |
**Users Menu** |  |   |
|  |   |
Delete a guest user in user's menu | The user is deleted and no longer available in oC. Check that user disappears from sharetabviews | ✅  |
Try to create a guest user in users menu adding it to the guest_group| The user should not be created. A warning should be shown | ✅  | No warning shown. Cosmetic bug. User is created and seems to be added to guest group. Refreshing the browser solves the issue
Change the guest user's password in users menu | The new password is set for the guest user | ✅  |
**Guest User account**|  |   |
|  |   |
Log in the guest user account  | Check that the shared file/folder appears with the right permissions | ✅ |
**Settings page**|  |   |
|  |   |
Change Guest Group name  | The group name for guest is changed. Check this change in Users Page and the shares are kept |✅  |
Set Guest Group name as empty  | A warning error should be shown and the previous name should be kept |✅ |
Limit guest access to an app whitelist checked, modify the list and save  | Check that only apps listed are available for guests users | ✅ |
**WebUI and browsers**|  |   |
|  |   |
Check that guests menu in sharing section works fine using FireFox as browser |  | ✅  |
Check that guests menu in sharing section works fine using Chrome as browser |  |✅|
Check that guests menu in sharing section works fine using IE11 as browser |  | Not tested |
Check that guests menu in sharing section works fine using Edge as browser |  | Not tested  |
Check that guests menu in sharing section works fine using Safari as browser |  | ✅  |

**Note** Translations works fine in German Formlich and Arabic ✅

**Comment by davitol** [comment]
## Changelog

### Fixed

- [ ] Use rawurldecode for allowing "+" in guests emails - [#384](https://github.com/owncloud/guests/issues/384)
- [ ] Use model addShare instead of share api while wrapping ShareDialogView - [#369](https://github.com/owncloud/guests/issues/369)

### Changed

- Bump libraries

**Comment by phil-davis** [comment]
@davitol to use a `+` in a guest username/email-address definitely requires core 10.4.0.

But if somebody wants the change in #369 then probably guests 0.8.3 will work fine with core 10.3.2 as long as users do not try to invite guests like `john+joan@example.com` - so we could do manual testing of that combination if we want to try to make a release that allows installing with core 10.3.2.

The change in #369 is not critical (it has been in master since Oct 2019 already). So maybe users will be OK with requiring core 10.4.0 ? @HanaGemela @micbar opinion?
