### ISSUE TITLE
screenshots and category is missing

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/guests#41]

**Comment by felixheidecke** [comment]
How should they look? Is it for the marketplace?

**Comment by PVince81** [comment]
It's for the marketplace, yes

**Comment by felixheidecke** [comment]
1, 2 or three? Resolution? Aspect Ratio?

**Comment by PVince81** [comment]
From what I saw you already posted screenshots, so you should know the guidelines: https://github.com/owncloud/screenshots (scroll down for readme)

But @IljaN already created a screenshot, not sure if he followed the guidelines.

Now only the category in info.xml is missing.

**Comment by DeepDiver1975** [comment]
screenshot is there - category is there -> close
