### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by PVince81** [owncloud/guests#43]
@IljaN @SergioBertolinSG @davitol please cooperate to make this happen

**Comment by IljaN** [comment]
@SergioBertolinSG Do we have a PhantomJS or Selenium test-suite where we can just click trough the interface?

**Comment by SergioBertolinSG** [comment]
@IljaN Well that looks more than functional tests. Perhaps out of scope here.

Anyway there are recent ui tests located here https://github.com/owncloud/core/tree/master/tests/ui

You could use them following this little guide: 
https://github.com/owncloud/core/wiki/Running-UI-tests-using-selenium

**Comment by patrickjahns** [comment]
@PVince81 - can be closed as we have https://github.com/owncloud/guests/tree/master/tests/acceptance

If we need further acceptance tests, please provide requirements
