### ISSUE TITLE
Error on adding "guest_app" group to user; No Feedback in UI

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/guests#431]
### Steps to reproduce
A)
1. Open user administration (/index.php/settings/users)
2. Create new user, select group "guest_app"
3. Click "Create"

OR

B)
1. Add group "guest_app" in Groups column on a existing user

### Expected behaviour
A) New created user is expected to be created as guest user (member of group "guest_app")
B) Existing user is added to the group "guest_app" (= converted to guest user account)

OR

In case of an error show an error message.

### Actual behaviour
In both cases the user is not added to the group "guest_app". The AJAX call to togglegroups.php when adding the group "guest_app" to a existing user gets a `{status: error}` JSON response.
In both cases (A) and B)) the possibility to add the user to the group"guest_app" suggests that this is possible. In both cases no error message is shown. The admin is let to believe to have created a guest user account.

#### Special case ownCloud.online:
Guest accounts are free of charge, normal user accounts initate a payment process. Customers are wondering why they get charged when adding free guest users via the user administration.

### Server configuration
Latest official OC Docker release (oC 10.5)
Guest app v0.9

**Comment by pmaier1** [comment]
Migrating regular users to guest users (and vice versa) is not supported in ownCloud 10. We should add a telling error message when an admin tries to do so.

**Comment by JammingBen** [comment]
> Migrating regular users to guest users (and vice versa) is not supported in ownCloud 10. We should add a telling error message when an admin tries to do so.

Will do :+1: Do you have a concrete suggestion for this message?

**Comment by JammingBen** [comment]
@pmaier1 Hmm, another idea came to my mind. If migrating users to guests (and vice versa) is not supported, why not just omit the "guest group"-option in corresponding menus? From my point of view, if I see a selectable element within a menu, I expect to be able to click it without an error.

![image](https://user-images.githubusercontent.com/50302941/104456954-b9cd3700-55a9-11eb-9a7b-9402b530ce34.png)

**Comment by pmaier1** [comment]
> why not just omit the "guest group"-option in corresponding menus? From my point of view, if I see a selectable element within a menu, I expect to be able to click it without an error.

Thanks! Agreed, that could be a better approach, yes.

**Comment by JammingBen** [comment]
@pmaier1 

Ok, here is what I did:

(1) Hide the "guest"-group in the menu when adding (or editing) users.
(2) Disable the group menus for existing guests as they are bound to the "guest"-group only.

Is it ok this way?

![image](https://user-images.githubusercontent.com/50302941/104565543-b6d75280-564c-11eb-9c9d-00dcf72b3561.png)

**Comment by pmaier1** [comment]
> (1) Hide the "guest"-group in the menu when adding (or editing) users.

:+1: 

> (2) Disable the group menus for existing guests as they are bound to the "guest"-group only.

Are they? I would expect to be able to add guests to any other group as well (while I can't remove them from the `guests_app` group, of course).

**Comment by JammingBen** [comment]
> Are they? I would expect to be able to add guests to any other group as well (while I can't remove them from the guests_app group, of course).

Ahhh ok, then I got that wrong :)
