### ISSUE TITLE
Update .drone.star to use the new owncloud-ci/node14 base

### ISSUE THREAD

**Issue by mmattel** [owncloud/guests#465]
See: https://github.com/owncloud/guests/blob/5f5cd2b16eea2ed0be606f7965d05f03698eb6cc/.drone.star#L969

Could be useful for the upcoming new release.

@phil-davis can you take a look on?

**Comment by phil-davis** [comment]
Done in #462 (part of overall issue https://github.com/owncloud/QA/issues/687 )

@mmattel I don't understand what you mean about that `php:7.2` use?

I know that we will likely drop PHP 7.2 soon, and as a separate issue, we should bump all these hard-coded uses of PHP to 7.4. I  will do that "so,e time soon" (tm).

And note that the code of `.drone.star` from `def main()` onwards is the same for almost all the oC10 "real" apps. When we have a general change to do, we make the change in the activity app (first in alphabetical order!) and then auto-create PRs to the other oC10 app repos.

**Comment by phil-davis** [comment]
Done in #490 "moving docker image references to constants" among many other drone starlark refactoring common to all oC10 apps.
