### ISSUE TITLE
guest can be made a subadmin of a group

### ISSUE THREAD

**Issue by phil-davis** [owncloud/guests#480]
### Steps to reproduce
1. share something with an email address to create a guest user guest@example.com
2. as an admin, on the user management page, select user guest@example.com to be the subadmin of some group
3. login as user guest@example.com and navigate to user management page

### Expected behaviour
I don't know - should guest users be able to be made a subadmin of a group?

### Actual behaviour
The guest user can change passwords of users in the group, delete users in the group etc.

### Server configuration
Current core master.

**Comment by phil-davis** [comment]
@JanAckermann @pmaier1 it seems to work OK.

Should there be something that prevents making a guest user into a group subadmin?

Similarly, a guest user can be added to the "admin" group (by an admin) and then they can do everything that an admin can do.

Should a guest user be able to be added to the "admin"  group?

**Comment by pmaier1** [comment]
> Should a guest user be able to be added to the "admin" group?

Currently I don't see a reason to prevent this. All good.

**Comment by phil-davis** [comment]
> Currently I don't see a reason to prevent this.

OK, then I am closing this issue.
