### ISSUE TITLE
Add UI tests for sharing settings guests blockdomains

### ISSUE THREAD

**Issue by phil-davis** [owncloud/guests#496]
PR #495 adds the ability to set the new guests "blockdomains" setting from the admin sharing settings panel:
![Guests-blocked-domains](https://user-images.githubusercontent.com/1535615/165439445-35bde9ae-e30f-4c67-893d-c5b1d9de127f.png)

Add webUI test scenario(s) that check this setting:
a) set from the command line `php occ config:app:set guests blockdomains --value="something.com,qwerty.org"`and check that the correct value is displayed in the UI
b) set/change from the UI and check that the correct value is shown from the command line:
```
$ php occ config:app:get guests blockdomains
zzz.com,abc.org
```
c) check for "unreasonable" strings (whatever gets decided is "unreasonable")

This probably needs a page-object to be set up for the admin sharing settings guest section of the UI, so it will be a good learning opportunity for someone who needs more exposure/experience of the oC10 webUI  test infrastructure.

**Comment by phil-davis** [comment]
"check for "unreasonable" strings (whatever gets decided is "unreasonable")"

no validation has been added in the code, so don't bother adding tests for invalid strings. Those can be added if-and-when validation is being added.

**Comment by SagarGi** [comment]
https://github.com/owncloud/guests/pull/500 PR adds 2 scenarios mentioned above. 
"Check for unreasonable string" Scenario is skipped untill then. So closing this issue
