### ISSUE TITLE
Improve UX for guest sharing blocklist

### ISSUE THREAD

**Issue by pmaier1** [owncloud/guests#498]
https://github.com/owncloud/guests/pull/495

Improve wording in the admin UI so that it is more self-explanatory. See proposal below and adapt it to the actual functionality, if necessary.

**Domain blocklist for guest user invitation**
The following domains will not be accepted when users try to invite guests. 
_Example: example1.com, example2.com, example3.com_

**Comment by mrow4a** [comment]
@pmaier1 needs release

**Comment by phil-davis** [comment]
> @pmaier1 needs release

See issue #499
