### ISSUE TITLE
Only load guest app js if in files app

### ISSUE THREAD

**Issue by IljaN** [owncloud/guests#51]
@felixheidecke requested this change to avoid collisions with other vue apps.

**Comment by PVince81** [comment]
collisions ? how that ? no namespacing ?

**Comment by felixheidecke** [comment]
Well … I added the vue.js file in the guest app without a namespace. I would like to bundle (and auto-namespace it) in the future. However, that would require a build process and that was dropped in favor of the 10 release.

BTW: Market-App is bundled and scoped btw. ;-)

**Comment by PVince81** [comment]
this kills the market app

**Comment by felixheidecke** [comment]
Can this be closed?
