### ISSUE TITLE
Add acceptance tests for "Limit guest access to an app whitelist"

### ISSUE THREAD

**Issue by phil-davis** [owncloud/guests#522]
The guests app can have settings like:
```
$ php occ config:list guests
{
    "apps": {
        "guests": {
            "blockdomains": "",
            "enabled": "yes",
            "group": "guest_app",
            "installed_version": "0.11.0",
            "signed": "true",
            "types": "authentication",
            "usewhitelist": "true",
            "whitelist": "settings,files_sharing,systemtags,files_trashbin,files_versions,comments"
        }
    }
}
```

These can be set from the `occ config:app:set` command, or from the classic webUI Admin Sharing settings panel.

If `usewhitelist` is set to true, then guests should only be able to see and use the apps in `whitelist`.

When an app is not in `whitelist` then it's API should not be able to be used by a guest, and its UI should not be displayed on the classic webUI.

Guests only have access to files/folders that are shared to them by real users on the system. So test scenarios will need a real user to first share resource(s) with a guest, and make some edits (to create versions), delete some file(s) in a shared folder (so that some items exist in the trashbin), make some comments, add some tags etc. Then the tests can verify that the guest user cannot see those things.

Add API acceptance tests to confirm:
- when comments is not in `whitelist` then a guest cannot view, add or delete comments on a resource
- when systemtags is not in `whitelist` then a guest cannot view tags, add tags or delete tags on a resource
- when files_versions is not in `whitelist` then a guest cannot view, add or delete versions of a resource
- when files_trashbin is not in `whitelist` then a guest cannot view, restore or delete the trashbin of a resource

Note: when a guest has write access to a resource, and files_trashbin/files_versions is not whitelisted, when the guest deletes/updates a resource, it is not yet decided if a new trashbin/version entry should be saved and available to the real user who shared the resource. That needs to be separately decided.

See #523 for the needed classic webUI tests.

**Comment by SwikritiT** [comment]
All the PRs for this issue have been merged closing this as completed
