### ISSUE TITLE
Wrong default permissions

### ISSUE THREAD

**Issue by PVince81** [owncloud/guests#55]
### Steps

1. Share a folder "test" with guest: type in a name "someone" to create a guest share
1. In the popup type email address and save
1. Receive email and set password
1. Login as "someone"
1. Enter folder "test": no permission to write, but "Rename" is visible
1. Log out
1. Login as the sharer
1. Check permissions: checkbox says "can edit"
1. Uncheck then check again the permission "can edit"
1. Login as "someone"
1. Enter folder "test": permissions are correct now

### Expected result
Permissions are correct in the first go.

### Actual result
The UI says the perms are "can edit" but actually it's a different perm.

Setting to critical because this is a bad first experience for a user even though there is a workaround. It makes it feel like the app is broken.

@IljaN please fix

cc @SergioBertolinSG

**Comment by PVince81** [comment]
Still happening for me on master (pulled both core master and guests).

After the first share I see the permissions being "3" in the database, this looks wrong:
```
+----+------------+---------------+-----------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-------+-----------+------------+
| id | share_type | share_with    | uid_owner | uid_initiator | parent | item_type | item_source | item_target | file_source | file_target | permissions | stime      | accepted | expiration | token | mail_send | share_name |
+----+------------+---------------+-----------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-------+-----------+------------+
|  1 |          0 | vincent_petry | admin     | admin         |   NULL | folder    | 14          | NULL        |          14 | /test       |           3 | 1492023567 |        0 | NULL       | NULL  |         0 | NULL       |
+----+------------+---------------+-----------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-------+-----------+------------+
```

If I uncheck the checkbox the permissions in DB become 1.

Then when I tick it again it becomes 15, which is correct.

So the bug is that for some reason the initial permissions is 3.

**Comment by IljaN** [comment]
So just to clarify again these are my initial permissions without touching anything:
![perms](https://cloud.githubusercontent.com/assets/246983/24996298/9cf018e2-2032-11e7-8290-b4ab3d179265.png)

On your side rename is missing despite "Can Edit" beeing checked?

**Comment by PVince81** [comment]
No, the bug is that I can't upload into that folder even though "can edit" is checked.

You can see on your screenshot that it says "You don't have permission to upload or create files here".

I didn't check the detailed initial permissions. Any reason why only "can change" is set by default and not "create" and "delete" ? Normally when creating new shares, all three are granted by default. Was there a decision to have the defaults different for guest users ? (this is very confusing)

cc @pmaier1

**Comment by IljaN** [comment]
Not sure, I see that permission "3" is hardcoded in the js

**Comment by pmaier1** [comment]
> Was there a decision to have the defaults different for guest users ?

I think the only difference was to have 'can share' default off which is the case. The permissions need to be applied though which is the issue here.

**Comment by IljaN** [comment]
https://github.com/owncloud/guests/blob/fe5ebacbe8b16219c5b39f280580361f0bdcd5eb/js/app.js#L118-L118

**Comment by PVince81** [comment]
Could be historical if it was in the old code.

Let's switch it to 15 then ? (compute it with OC.PERMISSION_* constants)

**Comment by IljaN** [comment]
Manually Tested
