### ISSUE TITLE
What is my user name ?

### ISSUE THREAD

**Issue by PVince81** [owncloud/guests#57]
### Steps

1. Receive guest account email
1. Open link and type password
1. Click "Reset password"
1. Stare at the login page not knowing what user name to enter

### Expected
Some form of hint that tells the guest user what user id to use.
Suggestions:
1) Add a hint about the user name in the email
2) Add a hint on the "forgotten password" page (this page will need to be customized at some point)
3) Prefill the login field with user name after forbidden password (might need core changes)

I think 1) should be easy to do quickly within the app.
The others are more changes in core in the way how "forgotten password" works.

**Comment by PVince81** [comment]
It is even more important for people who use email redirection / aggregators, so they might not know to which email you sent the invitation to so they can't guess the user name.

**Comment by IljaN** [comment]
Email address to login is now mentioned in invite mail.

**Comment by PVince81** [comment]
Thanks a lot!
