### ISSUE TITLE
Create guest by typing email address directly

### ISSUE THREAD

**Issue by PVince81** [owncloud/guests#58]
Currently you need to type in a name without "@" to be able to create a guest.

I find it more intuitive if I can first type in an email address to create a guest.
If a user typed in an email address, that one needs to be used in the popup and the focus goes to the "Name" field instead.

@felixheidecke

**Comment by pmaier1** [comment]
Yes, that would be perfect. As far as I remember @felixheidecke and had a chat about this already.

**Comment by pmaier1** [comment]
Btw. this can conflict with federated sharing. Is there a solution for this @PVince81 ?

**Comment by PVince81** [comment]
It doesn't really conflict, it would show two entries in the dropdown:
- "someone@example.com (remote)"
- "someone@example.com (guest)"

the problem is more one of UX and confusion

**Comment by cortho** [comment]
fixed with #109
