### ISSUE TITLE
Creating a share for an existing mail address should share with that user instead

### ISSUE THREAD

**Issue by pmaier1** [owncloud/guests#65]
- Creating a share entering a mail address that already exists for a user currently does not work and does not throw an error. 
- It should actually share with the existing user (no guest account creation) and inform the user about it. 
- Best would be to display a message right below the mail input field in the modal saying "The entered e-mail address is assigned to an existing user. Hit 'Share' to share with 'user'.
- As the address can probably only be checked after sending the form (?!) we might need another solution?

Related to https://github.com/owncloud/guests/issues/58. In this case it should just suggest the respective user in the dropdown.

@IljaN @PVince81 @felixheidecke

**Comment by PVince81** [comment]
I'm not sure it's the responsibility of the guest app to do that.

This basically introduces the concept of "autocomplete by user's email" which should likely be a core feature. Currently you can enter either user id or display name in the share field. We should probably add email address there as well, as long as that one is unique and if allowed by an admin. (some admins might want to disable search by email).

Then once we have this, the guest app doesn't need any modifications: when typing an email address, there will already be a result displayed so the guest app won't show its own "Guest" entry.

**Comment by PVince81** [comment]
Well, maybe not "autocomplete by user's email" because that implies typing partial email addresses.

Let's reword as: if a user enters a full valid email address in the sharing field and there is a unique user with that email address, then show that user in the selection.

@pmaier1

**Comment by pmaier1** [comment]
Ok, sounds reasonable. Anyway with the current guest app just nothing happens when you hit the button if you entered an existing mail address. At least this is not acceptable for the release.

**Comment by PVince81** [comment]
> Anyway with the current guest app just nothing happens when you hit the button if you entered an existing mail address. At least this is not acceptable for the release.

Agreed, this should be prevented.

**Comment by PVince81** [comment]
> sounds reasonable

new enhancement ticket for core ?

**Comment by pmaier1** [comment]
yes, please ;)

**Comment by felixboehm** [comment]
Please open a bug ticket in core. Sharing should also work with existing emails.

**Comment by felixboehm** [comment]
Follow Up https://github.com/owncloud/guests/issues/81
