### ISSUE TITLE
Improve the creation modal

### ISSUE THREAD

**Issue by pmaier1** [owncloud/guests#68]
- Headline: Change “Add ‘user’ to guests” to “Share with guest ‘user’”
- Input field ‘Username’ is greyed out. If not used there please remove it.
- Change button 'Save and Share' to 'Share'

@felixheidecke

**Comment by felixheidecke** [comment]
See https://github.com/owncloud/guests/pull/80

**Comment by PVince81** [comment]
was everything adressed in https://github.com/owncloud/guests/pull/80 which you reviewed @pmaier1 ?

if yes, please close
