### ISSUE TITLE
Improve naming of guest accounts

### ISSUE THREAD

**Issue by pmaier1** [owncloud/guests#69]
Is it possible to either call them like the mail address specified (‘name_provider_com’ does not look nice)? The entered name would also be an option, could conflict with existing users though.

@IljaN @felixheidecke

**Comment by cortho** [comment]
Plus, the underscores are created at client side only (app.js). So if I'll PUT to /apps/guests/users I am able to send anything, which might cause inconsistencies.

**Comment by IljaN** [comment]
Maybe we can remove the username from the ui alltogether because the guest user is promted to login via email address anyway

**Comment by felixheidecke** [comment]
The username has been removed via https://github.com/owncloud/guests/pull/80

**Comment by IljaN** [comment]
:+1:

**Comment by felixheidecke** [comment]
@pmaier1 is that satisfactory? We can close this issue then.

**Comment by pmaier1** [comment]
Does anything speak against just using the mail addresses as user names? Why do we need the underscores?

> Plus, the underscores are created at client side only (app.js). So if I'll PUT to /apps/guests/users I am able to send anything, which might cause inconsistencies.

I guess we should prevent this, right?

**Comment by pmaier1** [comment]
Assigning and setting milestone for overview

**Comment by cortho** [comment]
fixed with #109
