### ISSUE TITLE
guest app breaks other vuejy app - like market

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/guests#76]
![bildschirmfoto von 2017-04-25 19-08-05](https://cloud.githubusercontent.com/assets/1005065/25397980/9b064cd8-29ea-11e7-9775-1fae7bf35d9a.png)

**Comment by DeepDiver1975** [comment]
guests app 0.4

**Comment by davitol** [comment]
Fixed by https://github.com/owncloud/guests/pull/77
