### ISSUE TITLE
No error message in UI when duplicate email is used

### ISSUE THREAD

**Issue by tomneedham** [owncloud/guests#82]
Try to create a new guest with an email that is already being used

![screen shot 2017-05-11 at 15 02 30](https://cloud.githubusercontent.com/assets/660805/25953346/f55c708c-365a-11e7-963f-71c59b0bc5a1.png)

**Comment by cortho** [comment]
will be fixed with https://github.com/owncloud/guests/pull/109, so assigning this ticket

**Comment by cortho** [comment]
fixed with #109
