### ISSUE TITLE
Email notification resent when sharing with existing guest by email

### ISSUE THREAD

**Issue by PVince81** [owncloud/guests#84]
The code sends another notification every time you share with a guest using an existing email.

The mail template is different though: it's the generic "hey, a user shared XYZ" with you.
Normally this is the responsibility of the code share code to send these emails **if enabled by the admin**.

This looks like a bug. I think the mail handler in the guest app needs to check whether the guest user was just created and in this case send the mail. Else don't send anything.

@IljaN

**Comment by cortho** [comment]
@PVince81 @pmaier1 
This second email is provided intentionally, see https://github.com/owncloud/guests/blob/master/lib/hooks.php#L196

It is very easy to just remove these lines. Your opinions?

**Comment by cortho** [comment]
Just tested this out. Emails are sent to guests, when admin checks _Allow users to send mail notification for shared files to other users_ in Sharing settings, so I'll remove this functionality from the guests app.

**Comment by pmaier1** [comment]
> Just tested this out. Emails are sent to guests, when admin checks Allow users to send mail notification for shared files to other users in Sharing settings, so I'll remove this functionality from the guests app.

Fine :ok_hand: Share notification mails will still be sent when the settings is enabled, right?

**Comment by cortho** [comment]
> Share notification mails will still be sent when the setting is enabled, right?

yes, and only then

**Comment by cortho** [comment]
PR here: #139

**Comment by cortho** [comment]
fixed with #139
