### ISSUE TITLE
admin cannot see, when a guest user's password token is expired

### ISSUE THREAD

**Issue by cortho** [owncloud/guests#88]
and therefore admin cannot perform any further actions, depending on this information.

**Comment by pmaier1** [comment]
What's the use case here? Guest invited, token expired and no ability to invite again ending up in a zombie guest?

**Comment by pmaier1** [comment]
-> Overview page for pending guest invites that all users sharing with such guest can see in personal settings under section 'Guests'.

**Comment by pmaier1** [comment]
Assigning and setting milestone for overview

**Comment by cortho** [comment]
we do not use lostpassword functionality any more, fixed with #109
