### ISSUE TITLE
lostpassword expires too early

### ISSUE THREAD

**Issue by cortho** [owncloud/guests#93]
The guests app is using the lostpassword mechanism to leverage creation of guest users. There is the hard coded expiration of 12 hours at https://github.com/owncloud/core/blob/master/core/Controller/LostController.php#L165

While this might be sufficient for password recovery it is very likely that a potential guest user cannot register in this time.

This is especially annoying, as it is not possible to resend the registration email. (see https://github.com/owncloud/guests/issues/87 )

**Comment by PVince81** [comment]
I think we should anyway move away from using lost password and use an own page: https://github.com/owncloud/guests/issues/64

@IljaN @pmaier1

**Comment by pmaier1** [comment]
Assigning and setting milestone for overview

**Comment by cortho** [comment]
fixed with #109
